const SERVER_PORT = process.env.PORT || 4000;
const SUPABASE_DB_PASSWORD = process.env.SUPABASE_DB_PASSWORD;
const SUPABASE_PROJECT_API_KEY = process.env.SUPABASE_PROJECT_API_KEY;
const SUPABASE_PROJECT_URL = process.env.SUPABASE_PROJECT_URL;

export {
  SERVER_PORT,
  SUPABASE_DB_PASSWORD,
  SUPABASE_PROJECT_API_KEY,
  SUPABASE_PROJECT_URL,
};
